import {
  TermDrawAppRenderable,
  TermDrawEditorRenderable,
  TermDrawRenderable,
  buildHelpText,
  formatSavedOutput,
  type TermDrawAppRenderableOptions,
  type TermDrawEditorRenderableOptions,
  type TermDrawRenderableOptions,
} from "./app.js";
import {
  TERM_DRAW_COMMAND_CATALOG,
  getTermDrawCommandKeyLabel,
  type TermDrawCommandCatalogEntry,
  type TermDrawCommandEvent,
  type TermDrawCommandId,
  type TermDrawCommandKeyOptions,
  type TermDrawCommandLocus,
  type TermDrawCommandSource,
} from "./app/commands.js";
import {
  BRUSHES,
  BOX_STYLES,
  DRAW_DOCUMENT_VERSION,
  DrawState,
  INK_COLORS,
  LINE_STYLES,
  TEXT_BORDER_MODES,
  parseDrawDocument,
  validateDrawDocument,
  type BoxStyle,
  type CanvasInsets,
  type DrawCanvasCellKind,
  type DrawCanvasCellProjection,
  type DrawCanvasProjection,
  type DrawDocument,
  type DrawDocumentSnapshot,
  type DrawEditorSnapshot,
  type DrawMode,
  type DrawObject,
  type DrawStateSnapshot,
  type DrawViewportSnapshot,
  type ElbowOrientation,
  type InkColor,
  type LineStyle,
  type PointerEventLike,
  type TextBorderMode,
} from "./draw-state.js";
import {
  TERM_DRAW_APP_COMPONENT_NAME,
  TERM_DRAW_COMPONENT_NAME,
  TERM_DRAW_EDITOR_COMPONENT_NAME,
  TermDraw,
  TermDrawApp,
  TermDrawEditor,
  registerTermDrawComponent,
  registerTermDrawComponents,
  type TermDrawAppProps,
  type TermDrawEditorProps,
  type TermDrawProps,
} from "./react.js";

export {
  BRUSHES,
  BOX_STYLES,
  DRAW_DOCUMENT_VERSION,
  DrawState,
  INK_COLORS,
  LINE_STYLES,
  TEXT_BORDER_MODES,
  TERM_DRAW_COMMAND_CATALOG,
  TERM_DRAW_APP_COMPONENT_NAME,
  TERM_DRAW_COMPONENT_NAME,
  TERM_DRAW_EDITOR_COMPONENT_NAME,
  TermDraw,
  TermDrawApp,
  TermDrawAppRenderable,
  TermDrawEditor,
  TermDrawEditorRenderable,
  TermDrawRenderable,
  buildHelpText,
  formatSavedOutput,
  getTermDrawCommandKeyLabel,
  parseDrawDocument,
  registerTermDrawComponent,
  registerTermDrawComponents,
  validateDrawDocument,
  type BoxStyle,
  type CanvasInsets,
  type DrawCanvasCellKind,
  type DrawCanvasCellProjection,
  type DrawCanvasProjection,
  type DrawDocument,
  type DrawDocumentSnapshot,
  type DrawEditorSnapshot,
  type DrawMode,
  type DrawObject,
  type DrawStateSnapshot,
  type DrawViewportSnapshot,
  type ElbowOrientation,
  type InkColor,
  type LineStyle,
  type PointerEventLike,
  type TextBorderMode,
  type TermDrawAppProps,
  type TermDrawAppRenderableOptions,
  type TermDrawEditorProps,
  type TermDrawEditorRenderableOptions,
  type TermDrawCommandCatalogEntry,
  type TermDrawCommandEvent,
  type TermDrawCommandId,
  type TermDrawCommandKeyOptions,
  type TermDrawCommandLocus,
  type TermDrawCommandSource,
  type TermDrawProps,
  type TermDrawRenderableOptions,
};
